name: noting
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  awesome_dio_interceptor: ^1.0.0
  cupertino_icons: ^1.0.6
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_slidable: ^3.1.1
  gap: ^3.0.1
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.5.1

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SFPro/SF-Pro-Text-Heavy.otf
          weight: 700
        - asset: assets/fonts/SFPro/SF-Pro-Text-Bold.otf
          weight: 600
        - asset: assets/fonts/SFPro/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SFPro/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SFPro/SF-Pro-Text-Light.otf
          weight: 300
